### ISSUE TITLE
Build fails after `npm update`

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-client#73]
After I do `npm update` the build stops working with:

```
ERROR in ./src/vendor.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi vendor

ERROR in ./src/main.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main

ERROR in ./src/polyfills.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/home/gashcrumb/Work/src/ipaas-client/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi polyfills
```

**Comment by gashcrumb** [comment]
@kahboom @jimmidyson FYI...

**Comment by jimmidyson** [comment]
Looks like https://github.com/s-panferov/awesome-typescript-loader/issues/293

**Comment by jimmidyson** [comment]
Broken in https://github.com/Microsoft/TypeScript/pull/12373

**Comment by gashcrumb** [comment]
I love that :-)

**Comment by jimmidyson** [comment]
PR coming to freeze typescript version at 2.1.1

**Comment by gashcrumb** [comment]
awesome, thanks!
